### ISSUE TITLE
Benefit of hybrid cloudformation vs native terraform?

### ISSUE THREAD

**Issue by aaronsteers** [deanwilson/tf_sns_email#14]
Hello, I stumbled on this based on a google search, and I am considering leveraging this in another project. For my information, is there a strong reason why you chose to combine cloudformation and terraform, rather than building the entire configuration in terraform natively?

Thanks!

**Comment by aaronsteers** [comment]
Perhaps this is the reason?

https://medium.com/@raghuram.arumalla153/aws-sns-topic-subscription-with-email-protocol-using-terraform-ed05f4f19b73

>Terraform currently supports only sqs, sms, lambda, application (fully) and http, https (partially).
There is no support for email and email-json protocols because the endpoint needs to be authorized and does not generate an ARN until the target email address has been validated. This breaks the Terraform model and as a result, is not currently supported.

**Comment by deanwilson** [comment]
That's the very reason I originally wrote this so nice catch.

**Comment by deanwilson** [comment]
I'm not saying this model is the right one for different use cases but at the time it was the one that did what I needed.

**Comment by aaronsteers** [comment]
Thanks very much!
