### ISSUE TITLE
passing tags to the CloudFormation Stack

### ISSUE THREAD

**Issue by afeld** [deanwilson/tf_sns_email#3]
Saw your note in the README. Would passing the tags as Parameters work?

* https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html
* https://www.terraform.io/docs/providers/aws/r/cloudformation_stack.html#parameters

**Comment by deanwilson** [comment]
I was waiting for maps to be a first class entity - thanks for raising this issue and keeping it alive :)

Resolved in #5
