### ISSUE TITLE
Release 0.1.0 is breaking for us

### ISSUE THREAD

**Issue by christianhaller** [deanwilson/tf_sns_email#6]
Hi @deanwilson 
thanks for your terraform module. We use it in a lot of stacks.

With release `0.1.0` our pipelines are crashing:

`user is not authorized to perform: cloudformation:DescribeStacks`

We decided not to adjust the policy and stay on `0.0.1` 😄 

````
module "admin-sns-email-topic" {
  source = "github.com/deanwilson/tf_sns_email.git?ref=0.0.1"
  display_name  = "${var.app} Alarm"
  email_address = "${var.email}"
  owner         = "Alarm"
  protocol      = "email"
  stack_name    = "${var.app}-sns-email"
}
````

**Comment by deanwilson** [comment]
Apologies for this, I'll try and have a look this week. I'm more worried that my tests runs didn't catch this issue.

**Comment by deanwilson** [comment]
I understand what you're hitting now (I think). With the addition of the Tags to the CloudFormation stack terraform will require the new permission to ensure the tags set are the same as the tags desired. If you're not using tags on your stacks everything should be fine as it is with the previous release.

Thank you for letting me know you use the code. Honestly wasn't expecting anyone but me to be using this.
