### ISSUE TITLE
provider version

### ISSUE THREAD

**Issue by madcat78** [deanwilson/tf_sns_email#8]
Hi Dean,
I've been using this plugin for a while, it's really useful!
I've probably found an issue or maybe it's just me doing something wrong.

I had to update terraform aws provider version to 1.33.0 (for some new feature) but I wasn't able to do so (I got the error **No provider "aws" plugins meet the constraint "\~> 1.30.0,\~> 1.33.0".** ) until I've managed to change my local version of _providers.tf_:

```
provider "aws" {
   region  = "${var.aws_region}"
   version = "~> 1.33.0"
 }
```

Is there a way to handle the provider upgrades?
If I share my terraform template it will give an error in the initialization phase until you change manually your _providers.tf_ file.
Regards

**Comment by deanwilson** [comment]
Apologies for not picking this up sooner, my notifications seem to be broken. I've merged a new PR #10 that should hopefully address your issue.

Thank you for raising this.
